package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"
	"sync-bridge-go/graph/model"
	appErrors "sync-bridge-go/internal/errors"
	"time"
)

// CreateEmployee is the resolver for the createEmployee field.
func (r *mutationResolver) CreateEmployee(ctx context.Context, data model.CreateEmployeeInput) (*model.Employee, error) {
	_, err := r.DB.ExecContext(ctx,
		"INSERT INTO employees (id, employee_id, first_name, middle_name, last_name, email, company, job_title) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
		data.ID, data.EmployeeID, data.FirstName, data.MiddleName, data.LastName, data.Email, data.Company, data.JobTitle,
	)
	if err != nil {
		appErr := appErrors.HandleDBError(err)
		return nil, appErr
	}

	emp, err := r.getEmployeeByID(ctx, data.ID)
	if err != nil {
		return nil, err
	}
	if emp == nil {
		return nil, fmt.Errorf("failed to retrieve newly created employee")
	}

	// Publish to subscription channel
	r.Broker.Publish(emp)

	return emp, nil
}

// UpdateEmployee is the resolver for the updateEmployee field.
func (r *mutationResolver) UpdateEmployee(ctx context.Context, id int64, data model.UpdateEmployeeInput) (*model.Employee, error) {
	existing, err := r.getEmployeeByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if existing == nil {
		return nil, nil
	}

	firstName := existing.FirstName
	if data.FirstName != nil {
		firstName = *data.FirstName
	}

	lastName := existing.LastName
	if data.LastName != nil {
		lastName = *data.LastName
	}

	email := existing.Email
	if data.Email != nil {
		email = *data.Email
	}

	middleName := existing.MiddleName
	if data.MiddleName != nil {
		middleName = data.MiddleName
	}

	company := existing.Company
	if data.Company != nil {
		company = data.Company
	}

	jobTitle := existing.JobTitle
	if data.JobTitle != nil {
		jobTitle = data.JobTitle
	}

	_, err = r.DB.ExecContext(ctx,
		"UPDATE employees SET first_name = ?, last_name = ?, email = ?, middle_name = ?, company = ?, job_title = ? WHERE id = ?",
		firstName, lastName, email, middleName, company, jobTitle, id,
	)
	if err != nil {
		appErr := appErrors.HandleDBError(err)
		return nil, appErr
	}

	return r.getEmployeeByID(ctx, id)
}

// DeleteEmployee is the resolver for the deleteEmployee field.
func (r *mutationResolver) DeleteEmployee(ctx context.Context, id int64) (bool, error) {
	res, err := r.DB.ExecContext(ctx, "DELETE FROM employees WHERE id = ?", id)
	if err != nil {
		return false, err
	}

	affected, err := res.RowsAffected()
	if err != nil {
		return false, err
	}

	return affected > 0, nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	return "Hello from Sync Bridge", nil
}

// Employees is the resolver for the employees field.
func (r *queryResolver) Employees(ctx context.Context, offset *int, limit *int) ([]*model.Employee, error) {
	safeOffset := 0
	if offset != nil && *offset > 0 {
		safeOffset = *offset
	}

	safeLimit := 10
	if limit != nil && *limit > 0 {
		safeLimit = *limit
	}

	rows, err := r.DB.QueryContext(ctx,
		"SELECT id, employee_id, first_name, middle_name, last_name, gender, email, phone_number, "+
			"date_of_birth, nationality, job_level, department, location, bank_account_number, "+
			"company, job_title, cost_center, start_date, employee_status, manager_id, manager_email, "+
			"last_modified_on, last_modified FROM employees ORDER BY id LIMIT ? OFFSET ?",
		safeLimit, safeOffset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	list := []*model.Employee{}
	for rows.Next() {
		emp, err := r.scanEmployee(rows)
		if err != nil {
			return nil, err
		}
		list = append(list, emp)
	}

	return list, nil
}

// Employee is the resolver for the employee field.
func (r *queryResolver) Employee(ctx context.Context, id int64) (*model.Employee, error) {
	return r.getEmployeeByID(ctx, id)
}

// SearchEmployees is the resolver for the searchEmployees field.
func (r *queryResolver) SearchEmployees(ctx context.Context, search string, offset *int, limit *int) ([]*model.Employee, error) {
	safeOffset := 0
	if offset != nil && *offset > 0 {
		safeOffset = *offset
	}

	safeLimit := 10
	if limit != nil && *limit > 0 {
		safeLimit = *limit
	}

	searchPattern := "%" + strings.ToLower(search) + "%"

	rows, err := r.DB.QueryContext(ctx,
		"SELECT id, employee_id, first_name, middle_name, last_name, gender, email, phone_number, "+
			"date_of_birth, nationality, job_level, department, location, bank_account_number, "+
			"company, job_title, cost_center, start_date, employee_status, manager_id, manager_email, "+
			"last_modified_on, last_modified FROM employees "+
			"WHERE lower(first_name) LIKE ? OR lower(last_name) LIKE ? OR lower(email) LIKE ? "+
			"ORDER BY id LIMIT ? OFFSET ?",
		searchPattern, searchPattern, searchPattern, safeLimit, safeOffset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	list := []*model.Employee{}
	for rows.Next() {
		emp, err := r.scanEmployee(rows)
		if err != nil {
			return nil, err
		}
		list = append(list, emp)
	}

	return list, nil
}

// EmployeeCreated is the resolver for the employeeCreated field.
func (r *subscriptionResolver) EmployeeCreated(ctx context.Context) (<-chan *model.Employee, error) {
	ch := r.Broker.Subscribe()
	go func() {
		<-ctx.Done()
		r.Broker.Unsubscribe(ch)
	}()
	return ch, nil
}

// Resolver helpers

func (r *Resolver) getEmployeeByID(ctx context.Context, id int64) (*model.Employee, error) {
	rows, err := r.DB.QueryContext(ctx,
		"SELECT id, employee_id, first_name, middle_name, last_name, gender, email, phone_number, "+
			"date_of_birth, nationality, job_level, department, location, bank_account_number, "+
			"company, job_title, cost_center, start_date, employee_status, manager_id, manager_email, "+
			"last_modified_on, last_modified FROM employees WHERE id = ?", id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	if !rows.Next() {
		return nil, nil
	}

	return r.scanEmployee(rows)
}

func (r *Resolver) scanEmployee(rows *sql.Rows) (*model.Employee, error) {
	var emp model.Employee
	var dobStr, startDateStr, lastModOnStr sql.NullString

	err := rows.Scan(
		&emp.ID,
		&emp.EmployeeID,
		&emp.FirstName,
		&emp.MiddleName,
		&emp.LastName,
		&emp.Gender,
		&emp.Email,
		&emp.PhoneNumber,
		&dobStr,
		&emp.Nationality,
		&emp.JobLevel,
		&emp.Department,
		&emp.Location,
		&emp.BankAccountNumber,
		&emp.Company,
		&emp.JobTitle,
		&emp.CostCenter,
		&startDateStr,
		&emp.EmployeeStatus,
		&emp.ManagerID,
		&emp.ManagerEmail,
		&lastModOnStr,
		&emp.LastModified,
	)
	if err != nil {
		return nil, err
	}

	// Parse date of birth
	if dobStr.Valid && dobStr.String != "" {
		if t, err := parseTime(dobStr.String); err == nil {
			emp.DateOfBirth = &t
		}
	}

	// Parse start date
	if startDateStr.Valid && startDateStr.String != "" {
		if t, err := parseTime(startDateStr.String); err == nil {
			emp.StartDate = &t
		}
	}

	// Parse last modified on
	if lastModOnStr.Valid && lastModOnStr.String != "" {
		if t, err := parseTime(lastModOnStr.String); err == nil {
			emp.LastModifiedOn = &t
		}
	}

	// Compute full name
	parts := []string{}
	if strings.TrimSpace(emp.FirstName) != "" {
		parts = append(parts, emp.FirstName)
	}
	if emp.MiddleName != nil && strings.TrimSpace(*emp.MiddleName) != "" {
		parts = append(parts, *emp.MiddleName)
	}
	if strings.TrimSpace(emp.LastName) != "" {
		parts = append(parts, emp.LastName)
	}
	emp.FullName = strings.Join(parts, " ")

	return &emp, nil
}

func parseTime(s string) (time.Time, error) {
	layouts := []string{
		time.RFC3339,
		"2006-01-02T15:04:05Z",
		"2006-01-02 15:04:05",
		"2006-01-02",
	}
	for _, layout := range layouts {
		if t, err := time.Parse(layout, s); err == nil {
			return t, nil
		}
	}
	return time.Time{}, errors.New("unable to parse time: " + s)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
