/**
 * Data Transfer Object for Customer creation or update.
 */
export interface CustomerBodyDto {
  email: string;
  first_name: string;
  last_name: string;
}

/**
 * Data Transfer Object for Product creation or update.
 */
export interface ProductBodyDto {
  name: string;
  description: string;
  price: number;
  currency: string;
  active: boolean;
  weight_grams: number;
}

/**
 * Data Transfer Object for items within an Order.
 */
export interface OrderItemBodyDto {
  product_id: number;
  qty: number;
  unit_price: number;
}

/**
 * Data Transfer Object for Order creation or update.
 * Some fields might be handled by the backend logic.
 */
export interface OrderBodyDto {
  /**
   * @note Typically generated by the database on creation.
   * May be required for update operations.
   */
  id: number;

  /**
   * @note Typically generated by the server on creation.
   */
  order_number: string;

  customer_id: number;

  /**
   * @note Usually has a default value (e.g., 'pending') on creation.
   */
  status: string;

  currency: string;

  /**
   * @note Can be calculated on the server from 'items' for security and accuracy.
   */
  amount: number;

  items: OrderItemBodyDto[];
}
