// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateEmployeeInput struct {
	ID         int64   `json:"id"`
	EmployeeID string  `json:"employeeId"`
	FirstName  string  `json:"firstName"`
	LastName   string  `json:"lastName"`
	Email      string  `json:"email"`
	MiddleName *string `json:"middleName,omitempty"`
	Company    *string `json:"company,omitempty"`
	JobTitle   *string `json:"jobTitle,omitempty"`
}

type Employee struct {
	ID                int64      `json:"id"`
	EmployeeID        string     `json:"employeeId"`
	FirstName         string     `json:"firstName"`
	MiddleName        *string    `json:"middleName,omitempty"`
	LastName          string     `json:"lastName"`
	Gender            *string    `json:"gender,omitempty"`
	Email             string     `json:"email"`
	PhoneNumber       *string    `json:"phoneNumber,omitempty"`
	DateOfBirth       *time.Time `json:"dateOfBirth,omitempty"`
	Nationality       *string    `json:"nationality,omitempty"`
	JobLevel          *string    `json:"jobLevel,omitempty"`
	Department        *string    `json:"department,omitempty"`
	Location          *string    `json:"location,omitempty"`
	BankAccountNumber *string    `json:"bankAccountNumber,omitempty"`
	Company           *string    `json:"company,omitempty"`
	JobTitle          *string    `json:"jobTitle,omitempty"`
	CostCenter        *string    `json:"costCenter,omitempty"`
	StartDate         *time.Time `json:"startDate,omitempty"`
	EmployeeStatus    *string    `json:"employeeStatus,omitempty"`
	ManagerID         *string    `json:"managerId,omitempty"`
	ManagerEmail      *string    `json:"managerEmail,omitempty"`
	LastModifiedOn    *time.Time `json:"lastModifiedOn,omitempty"`
	LastModified      *int64     `json:"lastModified,omitempty"`
	FullName          string     `json:"fullName"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type UpdateEmployeeInput struct {
	FirstName  *string `json:"firstName,omitempty"`
	LastName   *string `json:"lastName,omitempty"`
	Email      *string `json:"email,omitempty"`
	MiddleName *string `json:"middleName,omitempty"`
	Company    *string `json:"company,omitempty"`
	JobTitle   *string `json:"jobTitle,omitempty"`
}
